### ISSUE TITLE
Improve document

### ISSUE THREAD

**Issue by ymd-h** [keiohta/tf2rl#152]
In order to make tf2rl more friendly, I suggest updating of README and [Reference Site](https://keiohta.github.io/tf2rl/index.html).

- [x] Add Numbering at headings (#153) 
- [x] Make clearer that there are several ways of installation (#153)
- [x] Add Usage section (#153)
- [ ] Available option for each algorithm
  - [x] DQN (#156, #157)
  - [x] DDPG (#156, #157)
  - [x] CategoricalDQN (#157) 
  - [x] TD3 (#157)
  - [x] BiResDDPG (#157)
  - [x] VPG (#157)
  - [x] PPO (#157)
  - [x] SAC (#157)
  - [x] SAC+AE (#158)
  - [x] CURL (#158)
  - [x] GAIL (#158)
  - [x] GAIfO (#158)
  - [x] VAIL (#158)
  - [x] Trainer (#158)
  - [x] MPC Trainer (#158)
  - [x] ME-TRPO Trainer (#158)
  - [x] On Policy Trainer (#158)
  - [x] IRL Trainer (#158)
  - [ ] etc
- [ ] Difference between continuous/discrete algorithm usage (if exists)
- [ ] Ape-X and other special usage
- [ ] Write missing docstring for some classes
  - [x] DQN (#156, #157)
  - [x] DDPG (#156, #157)
  - [x] CategoricalDQN (#157) 
  - [x] TD3 (#157)
  - [x] BiResDDPG (#157)
  - [x] VPG (#157)
  - [x] PPO (#157)
  - [x] SAC (#157)   
  - [x] SAC+AE (#158)
  - [x] CURL (#158)
  - [x] GAIL (#158)
  - [x] GAIfO (#158)
  - [x] VAIL (#158)
  - [x] Trainer (#158)
  - [x] MPC Trainer (#158)
  - [x] ME-TRPO Trainer (#158)
  - [x] On Policy Trainer (#158)
  - [x] IRL Trainer (#158)
  - [ ] etc 
- [ ] Describe detail at sphinx reference site
  - [x] Adjust config to show [Google Style docstring](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) (#156)
  - [ ] etc
- [ ] Type Hinting
